### ISSUE TITLE
How can I sync issues ?

### ISSUE THREAD

**Issue by rkhayyat** [kingjan1999/glo-ci#3]
Hi and thx for the glo-ci, actually I followed your tuto video, and managed to trigger event when I move card in Glo, however I could not figure it out if I can sync issues from Gitlab into Glo or visevera so whenever I create issue in Glo it will be created in Gitlab, then I can create branch from an issue and doing it from Glo :)

Thanks in advanced for your reply

**Comment by kingjan1999** [comment]
Hi,

thank you very much for your interest in glo-ci! Unfortunately, the use case you described (syncing issues between GitLab and Glo) is not supported by this integration, as it strictly focuses on CI integration.
