### ISSUE TITLE
Can not start

### ISSUE THREAD

**Issue by AmirAlOmari** [kingjan1999/glo-ci#8]
Hello 👋,

Just found this project on gitkraken glo marketplace. I really want to try it, but unfortunately the `Login with GitKraken` button refers to broken link `https://glo-ci.backend.g.kluster.app/v1/auth/login/gitkraken?callback=https://glo-ci.king-jan1999.now.sh/login-callback`.

**Comment by kingjan1999** [comment]
Hi,

Thank you for reporting! I guess I forgot to start the docker container after restarting the server today. Will fix this tomorrow (and maybe I should do some kind of monitoring to avoid this)

**Comment by kingjan1999** [comment]
The server is up and running again!
